environment:
  matrix:
    - RUBY_VERSION: 24-x64
      PATH: PATH=C:\Ruby%RUBY_VERSION%\bin;c:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH%
    - RUBY_VERSION: 24
      PATH: PATH=C:\Ruby%RUBY_VERSION%\bin;c:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\MinGW;%PATH%

install:
  - bundle install
  - bundle exec rake compile

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test

build: off

branches:
  only:
    - master
