branches:
  only:
    - master

environment:
  matrix:
    - RUBY_VERSION: 24-x64
      DEVKIT: C:\Ruby24-x64\DevKit
    - RUBY_VERSION: 24
      DEVKIT: C:\Ruby24\DevKit

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - "%DEVKIT%\\devkitvars.bat"
  - bundle install
  - bundle exec rake compile

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test
