install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - ruby --version
  - gem --version
  - bundle install
  - bundle exec rake compile

build: off

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"

branches:
  only:
    - master
